version: '3'
services:
  frontend: 
    build: ./trainee-frontend
    container_name: react-ui
    restart: always
    ports:
      - "5001:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-net

  backend: 
    build: ./trainee-backend
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - trainee_backend/.env
    depends_on:
      - database
    networks:
      - mern-net

  database:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mern-net
    volumes:
      - /home/shyam/mysqldb-backup:/data/db

  networks:
    mern-net:
      driver: bridge
